[package]
name = "leptatui"
version.workspace = true
edition.workspace = true

[dependencies]
crossterm = "0.29.0"
leptos = { version = "0.9.0-alpha", default-features = false, features = [
    "csr",
] }
ratatui = { version = "0.30.0", default-features = false, features = [
    "crossterm_0_29",
] }
thiserror = "2.0.18"
tokio = { version = "1.52.3", default-features = false, features = ["rt"] }

[dev-dependencies]
leptatui-macros = { path = "../leptatui-macros" }
tokio = { version = "1.52.3", default-features = false, features = [
    "macros",
    "rt-multi-thread",
] }
trybuild = "1"
