/// Verifies style modules store typed variables and mixins.
///
/// # Example Under Test
///
/// ```text
/// StyleModule::new()
///     .variable("fg", Color::Black)
///     .variable("surface", theme_color("surface"))
///     .mixin("control", StyleDeclarations::new().foreground(Color::Black))
/// ```
///
/// # Assertions
///
/// - Literal color variables are stored as color style values.
/// - Theme color variables are returned from the color getter.
/// - Visual and layout variables use typed getters.
/// - Stored mixins can be retrieved by name.
///
/// # Why
///
/// Imported stylesheet modules rely on typed runtime lookups generated by the
/// `stylesheet!` macro.
#[test]
fn style_module_stores_typed_variables_and_mixins() {
    let control = StyleDeclarations::new()
        .foreground(Color::Black)
        .padding(TuiSpacing::uniform(1));
    let module = StyleModule::new()
        .variable("fg", Color::Black)
        .variable("surface", theme_color("surface"))
        .variable("modifier", Modifier::BOLD)
        .variable("borders", Borders::ALL)
        .variable("border_type", BorderType::Rounded)
        .variable("padding", TuiSpacing::uniform(1))
        .variable("thumbnail", TuiSize::new(24, 8))
        .variable("display", Display::Grid)
        .variable("box_sizing", BoxSizing::BorderBox)
        .variable("overflow", Axes::new(Overflow::Hidden, Overflow::Auto))
        .variable(
            "layout_size",
            LayoutSize::new(Dimension::MinContent, Dimension::MaxContent),
        )
        .variable("edges", Edges::all(LengthAuto::Auto))
        .variable("gap", Axes::all(Length::cells(1.0)))
        .variable("flex_direction", FlexDirection::Column)
        .variable("flex_wrap", FlexWrap::Wrap)
        .variable("dimension", Dimension::from(Length::percent(25.0)))
        .variable("number", 2.0_f32)
        .variable("align_items", AlignItems::Center)
        .variable("align_self", AlignSelf::FlexEnd)
        .variable("align_content", AlignContent::SpaceAround)
        .variable("justify_items", JustifyItems::End)
        .variable("justify_self", JustifySelf::Center)
        .variable("justify_content", JustifyContent::SpaceEvenly)
        .variable("grid_auto_flow", GridAutoFlow::ColumnDense)
        .variable(
            "grid_line",
            GridLine::new(GridPlacement::line(1), GridPlacement::span(2)),
        )
        .variable("position", Position::Absolute)
        .variable("z_index", ZIndex::Integer(3))
        .mixin("control", control.clone());

    assert_eq!(
        module.get_value("fg"),
        Some(&StyleValue::Color(ThemeValue::Literal(Color::Black)))
    );
    assert_eq!(
        module.expect_color("surface"),
        ThemeValue::Variable(String::from("surface"))
    );
    assert_eq!(module.expect_modifier("modifier"), Modifier::BOLD);
    assert_eq!(module.expect_borders("borders"), Borders::ALL);
    assert_eq!(
        module.expect_border_type("border_type"),
        BorderType::Rounded
    );
    assert_eq!(module.expect_spacing("padding"), TuiSpacing::uniform(1));
    assert_eq!(module.expect_size("thumbnail"), TuiSize::new(24, 8));
    assert_eq!(module.expect_display("display"), Display::Grid);
    assert_eq!(
        module.expect_box_sizing("box_sizing"),
        BoxSizing::BorderBox
    );
    assert_eq!(
        module.expect_overflow("overflow"),
        Axes::new(Overflow::Hidden, Overflow::Auto)
    );
    assert_eq!(
        module.expect_layout_size("layout_size"),
        LayoutSize::new(Dimension::MinContent, Dimension::MaxContent)
    );
    assert_eq!(
        module.expect_length_auto_edges("edges"),
        Edges::all(LengthAuto::Auto)
    );
    assert_eq!(module.expect_gap("gap"), Axes::all(Length::cells(1.0)));
    assert_eq!(
        module.expect_flex_direction("flex_direction"),
        FlexDirection::Column
    );
    assert_eq!(module.expect_flex_wrap("flex_wrap"), FlexWrap::Wrap);
    assert_eq!(
        module.expect_dimension("dimension"),
        Dimension::from(Length::percent(25.0))
    );
    assert_eq!(module.expect_number("number"), 2.0);
    assert_eq!(module.expect_align_items("align_items"), AlignItems::Center);
    assert_eq!(module.expect_align_self("align_self"), AlignSelf::FlexEnd);
    assert_eq!(
        module.expect_align_content("align_content"),
        AlignContent::SpaceAround
    );
    assert_eq!(
        module.expect_justify_items("justify_items"),
        JustifyItems::End
    );
    assert_eq!(
        module.expect_justify_self("justify_self"),
        JustifySelf::Center
    );
    assert_eq!(
        module.expect_justify_content("justify_content"),
        JustifyContent::SpaceEvenly
    );
    assert_eq!(
        module.expect_grid_auto_flow("grid_auto_flow"),
        GridAutoFlow::ColumnDense
    );
    assert_eq!(
        module.expect_grid_line("grid_line"),
        GridLine::new(GridPlacement::line(1), GridPlacement::span(2))
    );
    assert_eq!(module.expect_position("position"), Position::Absolute);
    assert_eq!(module.expect_z_index("z_index"), ZIndex::Integer(3));
    assert_eq!(module.expect_mixin("control"), &control);
}

/// Verifies imported layout variables report incompatible stored kinds.
///
/// # Example Under Test
///
/// ```text
/// StyleModule::new()
///     .variable("layout", Axes::all(Overflow::Hidden))
///     .expect_display("layout")
/// ```
///
/// # Assertions
///
/// - The typed getter panics.
/// - The panic names the variable's stored kind and expected display kind.
///
/// # Why
///
/// Imported variables are checked at runtime, so their diagnostics must retain
/// stylesheet-oriented property context.
#[test]
#[should_panic(
    expected = "stylesheet module variable `$layout` is overflow, expected display"
)]
fn style_module_reports_incompatible_layout_variable_kinds() {
    StyleModule::new()
        .variable("layout", Axes::all(Overflow::Hidden))
        .expect_display("layout");
}

/// Verifies declaration merging overlays another declaration set.
///
/// # Example Under Test
///
/// ```text
/// StyleDeclarations::new()
///     .foreground(Color::White)
///     .background(Color::Black)
///     .merge(&StyleDeclarations::new().foreground(Color::Yellow))
/// ```
///
/// # Assertions
///
/// - Overlay declarations replace existing values.
/// - Missing overlay declarations preserve existing values.
/// - New overlay declarations are added.
///
/// # Why
///
/// Imported mixins compose by merging stored [`StyleDeclarations`] into an
/// in-progress declaration builder.
#[test]
fn style_declarations_merge_overlays_values() {
    let base = StyleDeclarations::new()
        .foreground(Color::White)
        .background(Color::Black);
    let overlay = StyleDeclarations::new()
        .foreground(Color::Yellow)
        .padding(TuiSpacing::uniform(1));

    assert_eq!(
        base.merge(&overlay),
        StyleDeclarations::new()
            .foreground(Color::Yellow)
            .background(Color::Black)
            .padding(TuiSpacing::uniform(1))
    );
}

/// Verifies important values ignore later normal declaration builder calls.
///
/// # Example Under Test
///
/// ```text
/// foreground_important(Red).foreground(Blue)
/// padding_important(1).padding(2)
/// ```
///
/// # Assertions
///
/// - The foreground remains the important red declaration.
/// - The padding remains the important uniform-one declaration.
///
/// # Why
///
/// Builder calls are used by stylesheet expansion and must preserve cascade
/// importance within a declaration set.
#[test]
fn style_declarations_important_values_ignore_later_normal_values() {
    assert_eq!(
        StyleDeclarations::new()
            .foreground_important(Color::Red)
            .foreground(Color::Blue)
            .padding_important(TuiSpacing::uniform(1))
            .padding(TuiSpacing::uniform(2)),
        StyleDeclarations::new()
            .foreground_important(Color::Red)
            .padding_important(TuiSpacing::uniform(1))
    );
}

/// Defines reusable color and spacing variables for imported macro tests.
fn imported_button_variables() -> StyleModule {
    stylesheet! {
        $fg: Color::Black;
        $bg: Color::White;
        $border: Borders::ALL;
        $border_type: BorderType::Rounded;
        $padding: TuiSpacing::uniform(1);
    }
}

/// Defines reusable button mixins for imported macro tests.
fn imported_button_mixins() -> StyleModule {
    stylesheet! {
        @use imported_button_variables as colors;

        @mixin primary {
            fg: colors.$fg,
            bg: colors.$bg,
            borders: colors.$border,
            border_type: colors.$border_type,
            padding: colors.$padding
        }

        @mixin inverted {
            @include primary,
            fg: colors.$bg,
            bg: colors.$fg
        }
    }
}

/// Verifies stylesheet macro imports variables and mixins from another module.
///
/// # Example Under Test
///
/// ```text
/// @use imported_button_mixins as button;
/// .submit => { @include button.primary }
/// .quit => { @include button.inverted }
/// ```
///
/// # Assertions
///
/// - A variable-only `stylesheet!` invocation returns a [`StyleModule`].
/// - A mixin-only `stylesheet!` invocation can import and use variables.
/// - A rule-producing `stylesheet!` invocation can include imported mixins.
/// - Imported mixin declarations preserve source-order overrides.
///
/// # Why
///
/// Reusable styles should be split across Rust modules without changing
/// stylesheet rule resolution behavior.
#[test]
fn stylesheet_macro_imports_variables_and_mixins() {
    let styles = stylesheet! {
        @use imported_button_mixins as button;

        .submit => { @include button.primary }
        .quit => { @include button.inverted }
    };

    let button_base = TuiStyle::new()
        .borders(Borders::ALL)
        .border_type(BorderType::Rounded)
        .padding(TuiSpacing::uniform(1));
    let expected = Stylesheet::new()
        .rule(
            StyleSelector::class("submit"),
            button_base
                .foreground(Color::Black)
                .background(Color::White),
        )
        .rule(
            StyleSelector::class("quit"),
            button_base
                .foreground(Color::Black)
                .background(Color::White)
                .foreground(Color::White)
                .background(Color::Black),
        );

    assert_eq!(styles, expected);
}
